=== MegasriDevaji/Web_Dev/WEB_Assignment/06-xml-schema/bookhub-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bookhub">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="author" type="xs:string"/>
                                        <xs:element name="category" type="xs:string"/>
                                        <xs:element name="price" type="xs:decimal"/>
                                        <xs:element name="stock" type="xs:int"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MegasriDevaji/Web_Dev/WEB_Assignment/06-xml-schema/bookhub-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookhub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="bookhub-schema.xsd">
    <books>
        <book id="B501">
            <title>Wings of Fire</title>
            <author>A. P. J. Abdul Kalam</author>
            <category>Biography</category>
            <price>300</price>
            <stock>40</stock>
        </book>
        <book id="B502">
            <title>Refactoring</title>
            <author>Martin Fowler</author>
            <category>Programming</category>
            <price>850</price>
            <stock>9</stock>
        </book>
        <book id="B503">
            <title>The Monk Who Sold His Ferrari</title>
            <author>Robin Sharma</author>
            <category>Self Help</category>
            <price>420</price>
            <stock>26</stock>
        </book>
    </books>
</bookhub>
